name: "Deploy to NuGet"

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'iParaClientService/iParaClientService.csproj'
  SOLUTION_PATH: 'iParaClientService.sln'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
   
     
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5      
      
    - name: Restore nuget packages
      run: nuget restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: msbuild ${{ env.PROJECT_PATH }} /p:Configuration=Release

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Pack project'
      run: nuget pack ${{ env.PROJECT_PATH }} -Properties Configuration=Release -Version ${{ steps.version.outputs.version-without-v }} -OutputDirectory ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package'
      run: nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg  ${{ secrets.NUGET_AUTH_TOKEN }} -Source ${{ env.NUGET_SOURCE_URL }}
      
   


    
